spring.application.name=E-sharing

# URL di connessione al database Oracle
spring.datasource.url=jdbc:oracle:thin:@//ttacademy.cpyk464koqyy.eu-west-3.rds.amazonaws.com:1521/TTA

# Credenziali di accesso
spring.datasource.username=sdimauro
spring.datasource.password=pippobaudo92

# Gestione DDL automatico
spring.jpa.hibernate.ddl-auto=update

# Visualizzare le query SQL in console
spring.jpa.show-sql=true




